### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by V1lu0** [iTeam-co/python-telegram#1]
windwos10,Python 3.9.6,use the example code

I used to use python3 in other versions,All the errors are here`from pytglib.client import Telegram`
```
from pytglib.client import Telegram

# Change the values below
api_id = ******
api_hash = '******'
phone_number = '+******'
dbenc = '******'

# Initiate the client
client = Telegram(api_id=api_id, api_hash=api_hash, phone=phone_number, database_encryption_key=dbenc)

# Login to the client
client.login() 

# Define the handler function
def my_message_handler(update):
    print(update)

# Register it
client.add_message_handler(my_message_handler)

tg.idle()

# And you're ready to go!
```
```
C:\Users\******\python3>python 1.py
Traceback (most recent call last):
  File "C:\Users\******\python3\1.py", line 1, in <module>
    from pytglib.client import Telegram
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 664, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 627, in _load_backward_compatible
  File "<frozen zipimport>", line 259, in load_module
  File "D:\******\Python39\lib\site-packages\pytglib-0.4-py3.9.egg\pytglib\client.py", line 18, in <module>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 664, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 627, in _load_backward_compatible
  File "<frozen zipimport>", line 259, in load_module
  File "D:\******\Python39\lib\site-packages\pytglib-0.4-py3.9.egg\pytglib\functions.py", line 9, in <module>
  File "D:\******\Python39\lib\site-packages\pytglib-0.4-py3.9.egg\pytglib\functions.py", line 214, in Function
TypeError: __init__() missing 1 required positional argument: 'horizontal_accuracy'
```

**Comment by WebShark025** [comment]
Use version 3.0

**Comment by V1lu0** [comment]
python3 ?

**Comment by V1lu0** [comment]
My python version is 3

**Comment by WebShark025** [comment]
3.6++

**Comment by V1lu0** [comment]
didn't work in Python 3.6.8

**Comment by jackchevalley** [comment]
same error on Python 3.8.10 (Linux - ubuntu 20 - nginx )

**Comment by WebShark025** [comment]
Fixed in latest commit, should work now.
